### ISSUE TITLE
QA: Improve registry changes

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#940]
Requesting making one function in phoenicis that can change registry on demand since current implementation is obsolete and terrible in comparison to lutris where it allows change directly in installer. 

Could be made using one function that expects path and value (format).

### Lutris example:
```yaml
installer:
- task:
    key: UseTakeFocus
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\X11 Driver
    prefix: $GAMEDIR
    value: N
```

### Phoenicis example
```javascript
include("engines.wine.engine.object");
include("engines.wine.plugins.regedit");

/**
 * setting to enable/disable UseTakeFocus
*/
var settingImplementation = {
    _options: [tr("Default"), tr("Disabled"), tr("Enabled")],
    // values which are written into the registry, do not translate!
    _registryValues: ["", "N", "Y"], // `Y` is blind code since it's enabled by default on wine-staging it seems
    getText: function () {
        return tr("UseTakeFocus");
    },
    getOptions: function () {
        return this._options;
    },
    getCurrentOption: function (container) {
        var currentValue = new Wine()
            .prefix(container)
            .regedit()
            .fetchValue(["HKEY_CURRENT_USER", "Software", "Wine", "X11 Driver", "UseTakeFocus"]);
        // find matching option (use default if not found)
        var index = Math.max(this._registryValues.indexOf(currentValue), 0);
        return this._options[index];
    },
    setOption: function (container, optionIndex) {
        if (0 == optionIndex) {
            new Wine()
                .prefix(container)
                .regedit()
                .deleteValue("HKEY_CURRENT_USER\\Software\\Wine\\X11 Driver", "UseTakeFocus");
        }
        else {
            var regeditFileContent =
                "REGEDIT4\n" +
                "\n" +
                "[HKEY_CURRENT_USER\\Software\\Wine\\X11 Driver]\n" +
                "\"UseTakeFocus\"=\"" + this._registryValues[optionIndex] + "\"\n";
            new Wine()
                .prefix(container)
                .regedit()
                .patch(regeditFileContent);
        }
    }
};

/* exported Setting */
var Setting = Java.extend(org.phoenicis.engines.EngineSetting, settingImplementation);

-----

// In installer
preInstall(function (wine, wizard) {
    wine.UseTakeFocus("disabled");
}
```

---

Relevant: https://github.com/PhoenicisOrg/scripts/issues/936

**Comment by ImperatorS79** [comment]
This whole implementation, as a settings, allow you to change it from the phoenicis interface. Do it as a verb and it is far easier. 

Also, your comparison is wrong. You should have compared like this:
In lutris:
```
installer:
- task:
    key: UseTakeFocus
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\X11 Driver
    prefix: $GAMEDIR
    value: N
```
in phoenicis:
```
preInstall(function (wine, wizard) {
    wine.UseTakeFocus("disabled");
}
```
