### ISSUE TITLE
Add Minion Master

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#957]
Works on staging, requires UseTakeFocus disabled.

Graphical glitches present,

Steam required, investigate discord installer

Add DXV9

### Lutris installer
```yaml
files:
- d9vk: https://github.com/Joshua-Ashton/d9vk/releases/download/0.11/d9vk-0.11.tar.gz
game:
  appid: 489520
  arch: win64
  prefix: $GAMEDIR/prefix
installer:
- extract:
    dst: $CACHE/d9vk-0.11/
    file: d9vk
- copy:
    dst: $HOME/.local/share/lutris/runtime/dxvk/d9vk-0.11/
    src: $CACHE/d9vk-0.11/dxvk-release/
- task:
    arch: win64
    description: Creating Wine prefix.
    name: create_prefix
    prefix: $GAMEDIR/prefix
- task:
    app: usetakefocus=disabled
    arch: win64
    description: Disabling UseTakeFocus contributed by our God Kreyren (https://github.com/Winetricks/winetricks/pull/1246)
    name: winetricks
    prefix: $GAMEDIR/prefix
system:
  env:
    DXVK_HUD: 0
    DXVK_LOG_LEVEL: none
    DXVK_STATE_CACHE_PATH: $GAMEDIR/prefix
    __GL_SHADER_DISK_CACHE: 1
    __GL_SHADER_DISK_CACHE_PATH: $GAMEDIR/prefix
    __GL_THREADED_OPTIMIZATIONS: 1
wine:
  dxvk: true
  dxvk_version: d9vk-0.11
  version: ge-protonified-4.9-x86_64
```
